### ISSUE TITLE
robot_V3.py  the file is MISSING?

### ISSUE THREAD

**Issue by MorrisLu-Taipei** [NiryoRobotics/ned_applications#1]
Hi all,

as tutorial - `[Leap Motion hand tracking controller](https://www.docs.niryo.com/applications/ned/source/examples/control_ned_leap_motion)` shown, 
We did the Leap motion installation and works fine.

BUT couldn't find robot_V3.py  (which folder? )
Section : How to launch the application - Link the Leap library to your code
any hints or sample file of robot_V3.py?

Thanks millions

**Comment by MorrisLu-Taipei** [comment]
I guess robot_v3.py is leap_motion_ned.py
try to figure it out

**Comment by Wasta-Geek** [comment]
Hi,
Thank you for your report.
It's correct, robot_v3.py is indeed leap_motion_ned.py, the part about "link the leap library to your code" in the documentation was changed in the code but not corrected in the documentation, we will fix the documentation online.
The leaplib is already provided in the folder "leaplib" now so you shouldn't need to changed this part, it should works natively without changing this.
